export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';

export const LOGOUT_START = 'LOGOUT_START';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';

// game actions
export const START_GAME = 'START_GAME';
export const RESET_GAME = 'RESET_GAME';

export const FETCH_QUIZ_START = 'FETCH_QUIZ_START';
export const FETCH_QUIZ_SUCCESS = 'FETCH_QUIZ_SUCCESS';
export const FETCH_QUIZ_FAIL = 'FETCH_QUIZ_FAIL';
export const FETCH_QUIZ_CANCEL = 'FETCH_QUIZ_CANCEL';

export const ANSWER_QUESTION = 'ANSWER_QUESTION';
export const NEXT_QUESTION = 'NEXT_QUESTION';
export const FINISH_GAME = 'FINISH_GAME';

// score
export const TIME_LEFT = 'TIME_LEFT';
export const ADD_SCOREBOARD = 'ADD_SCOREBOARD';
export const ADD_SCOREBOARD_FAIL = 'ADD_SCOREBOARD_FAIL';
export const FETCH_SCOREBOARD_START = 'FETCH_SCOREBOARD_START';
export const FETCH_SCOREBOARD_SUCCESS = 'FETCH_SCOREBOARD_SUCCESS';
export const FETCH_SCOREBOARD_FAIL = 'FETCH_SCOREBOARD_FAIL';

// reviews
export const ADD_REVIEW_START = 'ADD_REVIEW_START';
export const ADD_REVIEW_SUCCESS = 'ADD_REVIEW_SUCCESS';
export const ADD_REVIEW_FAIL = 'ADD_REVIEW_FAIL';

export const FETCH_REVIEWS_START = 'FETCH_REVIEWS_START';
export const FETCH_REVIEWS_SUCCESS = 'FETCH_REVIEWS_SUCCESS';
export const FETCH_REVIEWS_FAIL = 'FETCH_REVIEWS_FAIL';
